from . import slug_mixin
from . import workshop_type
from . import service
from . import vehicle_brand
from . import location
from . import workshop
from . import workshop_image
from . import review
from . import inquiry
from . import verification
from . import website
from . import res_config_settings
