from . import slug_mixin
from . import workshop_type
from . import service
from . import vehicle_brand
from . import location
from . import vehicle
from . import working_day
from . import workshop
from . import workshop_image
from . import offer
from . import review
from . import inquiry
from . import verification
from . import message
from . import website
from . import res_partner
from . import res_config_settings
# assistance, recovery and parts marketplace
from . import request
from . import part_offer
from . import notification
from . import workshop_services
